    INPUT N 
    LOAD N 
FAT: SUB ONE 
    JNPZ FIM 
    STORE AUX 
    MULT N 
FIM: STORE N ;rotulo declarado duas vezes
    LOAD AUX 
    JNP FAT 
FIM: OUTPUT N 
    STOP
AUX: SPACE 3
N: SPACE
ONE: CONST 1

COPY A, B 
ROT: COPY C, D
ULTIMA: COPY E, F